### ISSUE TITLE
Ignore entries without a password

### ISSUE THREAD

**Issue by OLLI-S** [andrew-schofield/keepass2-haveibeenpwned#41]
In KeePass I also have some entries that have no password in the "Password" field but other data (for example user-defined fields).
Have I Been Pwned tells me that the entry "Abandonia" is affected although I have no password stored here.
What about ignoring entries that do not have a password?

**Comment by me-and** [comment]
It looks to me like the behaviour you're asking for is supposed to already be present: https://github.com/andrew-schofield/keepass2-haveibeenpwned/blob/master/HaveIBeenPwned/BreachCheckers/HaveIBeenPwnedPassword/HaveIBeenPwnedPasswordChecker.cs#L74

Nonetheless, I agree that it doesn't appear to be working.

**Comment by andrew-schofield** [comment]
I believe this is fixed in 5f6cbc03d0deaae8d56388f530387f74db37b700 as a result of investigating #44 
The problem here appears to be that if you ticked the "check all breaches" box on the password check dialog, it actually runs the other types of check as well.

Creating an entry with no password (and even one with the name "Abandonia", now returns no results on the password checker.
