### ISSUE TITLE
Breach date always current date

### ISSUE THREAD

**Issue by m4xc4v413r4** [andrew-schofield/keepass2-haveibeenpwned#44]
It didn't use to be like this and it makes it harder to understand if we already changed that password.

When I lookup breaches it always gives me that the breach date is "today" for HIBP breaches, which is obviously not true, but without the actual breach date how can I compare it with the date of last change?

**Comment by andrew-schofield** [comment]
Which breach checker are you using?

The "password" checker will always return the current date.
Having just tried it locally, the site and username checkers appear to be working as expected for me (returning the actual breach date).

**Comment by m4xc4v413r4** [comment]
It's everything that shows under the "Breach Name" - "HIBP Password Breach" which is 99% of my list.

This shows even when I don't choose the "Check for breaches based on your password" option, I just tried the "... on site/service" and "... on username" and it's the same thing, I get a huge list of accounts, pretty much all of them are "HIBP Password Breach" with today's date, which makes it impossible to know if the password has been changed after the breach or not.

**Comment by andrew-schofield** [comment]
That sounds like something pretty strange is going on. If you select the site/service or username options, you shouldn't get entries in the results list that are from the "HIBP Password Breach"

**Comment by Jalfreziboy** [comment]
Hi I too have the same issue, using site / service search, with the all breaches option checked it returns a long list of  breaches from HIBP password breach with the current date, most of which have the same password which I am assuming has been breached at some point.

**Comment by Sanaki** [comment]
I just checked breaches by username to verify (site/service won't pull any up for me, but username has a number of non-applicable options and usernames like root or admin for some network equipment), and all breach dates show correctly. So far as I can personally verify, the issue was already fixed long ago. I have version 1.2.4 on KeePass 2.40 (on linux, though that shouldn't make any difference).

![breaches](https://user-images.githubusercontent.com/1374333/51232142-cccab380-195d-11e9-8461-d2740acad1d8.png)

**Comment by Jalfreziboy** [comment]
Hi thanks for your reply. I too have ver 1.2.4 but on keepass 2.41 on windows 10. I have tried removing and reapplying the plugin but now it returns and error (see screenshot) so not sure what's happening now. 
![image](https://user-images.githubusercontent.com/46519313/51240512-c0e9ec00-1973-11e9-84f3-2e377b25b0c3.png)

**Comment by Sanaki** [comment]
That one's unrelated, follow #56 for updates on that particular issue. Good luck!

**Comment by andrew-schofield** [comment]
> Hi I too have the same issue, using site / service search, with the all breaches option checked it returns a long list of breaches from HIBP password breach with the current date, most of which have the same password which I am assuming has been breached at some point. Did you ever resolve this issue?

No, sadly I haven't resolved this issue. The date being "today" is correct for any results returned for the "HIBP Password Breach" type, as this check has no data about when a password was breached (unless this is now included in the API response from HIBP).
The bug here is that the site/service check seems to also include results from the other checks as well.

**Comment by Jalfreziboy** [comment]
Thank you  but how do I apply this fix?

**Comment by andrew-schofield** [comment]
Download version 1.3, which contains the fix.
